
services:
  rest:
    container_name: inventory-manager
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/inventory_db
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    container_name: mysqlDB
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventory_db
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: {}
